color: true
dry-run: null
hookfiles: null
language: nodejs
require: null
server: npm start
server-wait: 3
init: false
names: false
only: []
reporter: ['dot', 'html', 'apiary']
output: ['build/test.html']
headers: []
sorted: false
user: null
inline-errors: false
details: false
method: []
loglevel: warning
path: []
config: ./dredd.yml
blueprint: api.apib
endpoint: 'http://127.0.0.1:4000'
